### ISSUE TITLE
[MIX] Sandboxed iframes as optionally-blockable Content

### ISSUE THREAD

**Issue by kyprizel** [w3c/webappsec#179]
Let's discuss it?

Related topic:
https://bugzilla.mozilla.org/show_bug.cgi?id=903211

**Comment by mikewest** [comment]
Since we've already shipped iframe blocking in Chrome, and I believe Firefox and IE have done the same, it seems as though the existential challenges raised in the bugzilla thread you've pointed to have been addressed.

Is there a particular use case that you'd have for sandboxed iframes?

**Comment by kyprizel** [comment]
Main case for me is something like https://translate.google.com which requires to translate some http resource. Now you have to make some http->https proxy, sanitize js etc.

**Comment by briansmith** [comment]
Eldar Zaitov <notifications@github.com> wrote:

> Main case for me is something like https://translate.google.com which
> requires to translate some http resource. Now you have to make some
> http->https proxy, sanitize js etc.
>
I suspect that when CSP 2 is published, there's going to be a huge increase
in the number of sites are going to prohibit framing via the
frame-ancestors directive (the replacement for X-Frame-Options). In fact,
everybody should be using frame-ancestors to prevent framing by default.
This means that, even independent of mixed content blocking policy, things
like Google Translate are going to have extreme difficulty without
implementing such proxies.

As far as I understand, the same applies to Google's ad preview mechanism.
Therefore, the idea of using iframes for these mechanisms seems like a lost
cause.

Cheers,
Brian

**Comment by kyprizel** [comment]
X-Frame-Options wasn't flexible enough b/c ALLOW-FROM didn't support multiple domains, "frame-ancestors" in opposite allows to specify list of trusted origins.
Use case - some analytics service needs to draw a heat map of clicks as a new visual layer on the clients resource. If you need client to send his cookies to the resource there are two solutions:
1. Run your code in the target resources origin (kind of dangerous)
2. Open it in the frame and overlay your data

**Comment by mikewest** [comment]
The behavior in the spec is implemented across user agents at this point, and without a compelling use case that requires sandboxed, insecure frames, it seems unlikely that we'll change things.

Given that the use case you've outlined (drawing an overlay on a client page) already requires analytics code to be running on the page (as data wouldn't be collected otherwise), it seems reasonable that clients have accepted the "kind of dangerous" behavior. I'd rather put that burden on individual clients for them to consider in contract negotiations than to bore a hole in the web's security model to support that small subset of entities.
