### ISSUE TITLE
CREDENTIAL: notifySingedOut() and require user mediation

### ISSUE THREAD

**Issue by jmajnert** [w3c/webappsec#198]
Why does the notifySingedOut() method require the UA to run the "require user mediation" algorithm?

**Comment by mikewest** [comment]
"signing out" is an instruction to the user agent to not automatically sign the user back in. Otherwise it wouldn't be very effective. The algorithm you've pointed to does that by flagging the origin as "requiring user mediation", e.g. not just handing a credential back to the origin, but requiring user activity in order to do so (by popping up a chooser or similar).

**Comment by jmajnert** [comment]
This is not what the method name implies... I thought that the method would allow UAs to present some sort of UI showing the user which services they are signed into at any moment.

Both signing in and out are performed by the web app, not by the UA. If the user did sign out of an app (for whatever reason), it is an action that the web app is aware of and thus can keep the user signed out until they explicitly choose to sign in again. The app can check the credential.id before trying to re-sign in, right?

**Comment by jmajnert** [comment]
If this method stays as it is now, a web app that wants to allow users to sign in and out with just a single button (after first setting up an account) will never call it. Thus the UA will not be notified about signing out.

**Comment by jmajnert** [comment]
I propose removing the "require user mediation" from notifySingedOut() or alternatively changing the method name to requireUserMediation().
Or, to satisfy both sides, we can just add requireUserMediation() to the API.

**Comment by mikewest** [comment]
1. Renaming is certainly a reasonable option.

2. The fact that we rely on the website to do the right thing is exactly the reason that we can't present some sort of UI showing the user where she's signed in. We don't know that, and we don't (shouldn't) trust the website to tell us. we should, however, give well-behaved apps the ability to do the right thing. They shouldn't need to maintain state about the user in order to determine whether or not they should ask who the user is. That's somewhat counterintuitive.

**Comment by jmajnert** [comment]
OK. Let's go with renaming then.

**Comment by jmajnert** [comment]
I think this can be closed as well?

**Comment by jmajnert** [comment]
Thanks
