### ISSUE TITLE
CREDENTIAL: use fetch()

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#241]
Instead of

    credential.send(url)

why not just

    fetch(url, {body:credential})

? Seems better than introducing yet another networking API. And perhaps allow it to be appended to `FormData` so you can add extra data too?

**Comment by mikewest** [comment]
I was just about to add something like:

```
credential.send({
  'endpoint': 'https://example.com/login',
  'usernameParameter': 'user',
  'passwordParameter': 'pass',
  'data': {
    'key1': 'value1',
    'key2': 'value2',
    ....
  }
});
```

Flipping it around to pass the object into Fetch might make sense... The property I care about is opacity for the private data in the Credential object; as long as we can integrate it with Fetch in a way that retains that opacity to JavaScript, I'm happy to defer to your preference.

Passing the credential object in as the body would require extending https://fetch.spec.whatwg.org/#concept-bodyinit-extract right?

**Comment by annevk** [comment]
Yeah, we'd have to extend that and support an opaque request body. Paging @domenic, @yutakahirano, @tyoshino, @wanderview, @jakearchibald to see if they have thoughts. It seems to me that could work similar to an opaque response, while perhaps still allowing access to the non-body parts of the request?

**Comment by mikewest** [comment]
I guess I'm less concerned about the ServiceWorker implications (if only because a ServiceWorker could already screw you over in a number of ways). Or are you saying that the request body is otherwise accessible via `fetch()`?

**Comment by annevk** [comment]
It would be accessible through `new Request()` unless we limit it somehow to `fetch()`, but the latter is something we have avoided thus far.

**Comment by mikewest** [comment]
I see. I guess I'd prefer that that not be possible. :)

**Comment by yutakahirano** [comment]
We have `text()`, `json()`, etc. on Request and Response as utility methods, but after introducing body stream, I think introducing a parser for each data representation (e.g. Document) is preferable than adding methods to Request and Response.

Similarly, I think having an encoder or something that writes a credential object into a WritableByteStream makes more sense than adding one more overloading. It can be `credential.writeInto(ws)`.

But I'm not sure how opacity works with this pattern.

**Comment by mikewest** [comment]
For background, something like https://mikewest.github.io/credentialmanagement/writeonly/#opaque-formdata is what I was hoping to avoid with the `send()` mechanism.

**Comment by annevk** [comment]
@yutakahirano I agree in general, especially for something as complex as `Document`, but credentials make some amount of sense to support directly at the network layer.

**Comment by domenic** [comment]
I'm not sure I fully understand this thread but I do think we probably want to introduce "OpaqueReadableStream" which has only pipeTo/pipeThrough/cancel and no getReader at some point.

**Comment by domenic** [comment]
OpaqueReadableStream should be pretty easy to specify too as most of its spec consists of "magic happens here."

**Comment by domenic** [comment]
Having read through CREDENTIALS I now understand this issue a bit better.

Since credentials are small streaming them is probably not necessary. We could still leverage (opaque) streams as a nice API conceit, but I am not sure. I guess one important question is do we ever want to write these credentials to any other stream-like thing besides fetch? If so then it makes more sense to use streams. If not then I'm still undecided.

If we were to use streams one approach would be to add `credential.toOpaqueStream()`, and either the author does `fetch(url, { body: credential.toOpaqueStream() })`, or we have Fetch try to auto-convert objects with toOpaqueStream methods so you can do `fetch(url, { body: credential })`. That way the fetch API is decoupled from the credentials concept.

Also, if we don't think streams are the right primitive here, we could still achieve some decoupling with opaque blobs if such a thing exists.

Finally I want to point out that in https://github.com/w3c/webappsec/issues/241#issuecomment-92240845 @mikewest gives a much more powerful mechanism than just `fetch(url, { body: credential })` would give, streaming or not. It allows adding other arbitrary keys, which indeed might be important. 

On the other hand even @mikewests's comment doesn't allow using basic auth headers or similar. And there are many more complicated protocols on the web already (e.g. hashing or hashing + salting before sending to the server). I think we are already going to be missing use cases if we don't allow authors the flexibility of seeing the password themselves. The question is where do we draw the line.

**Comment by annevk** [comment]
I think the best bet here is still opaque `FormData`. Opaque streams would come into play if we want to hide opaque `FormData` from service workers. `FormData` allows for adding key/value pairs and has a defined and widely supported serialization. Combined with `fetch()` and some restrictions on `fetch()` when used with opaque `FormData` we have the most flexibility and smallest API increase.

**Comment by domenic** [comment]
Opaque `FormData` makes sense. It would be write-only I assume, which is great since then you can add additional stuff to it.

So something like `credential.toFormData({ usernameField: "user", passwordField: "pass" })` (with defaults of `"username"` and `"password"`?

**Comment by annevk** [comment]
Yeah (I was thinking `usernameName`/`passwordName` since we refer to them as name/value, but either way).

**Comment by mikewest** [comment]
Ok. Then let's do that.

Who wants to be responsible for https://mikewest.github.io/credentialmanagement/writeonly/#opaque-formdata? I floated it on WHATWG a while back as part of https://lists.w3.org/Archives/Public/public-whatwg-archive/2014Oct/0181.html, to something marginally less than excitement.

I can certainly just slap it into this document, but it probably should live in XHR next to `FormData` itself?

**Comment by mikewest** [comment]
Although I still think it's much simpler for developers to call `send()` on the object, rather than something like

```
var formData = cred.toFormData(...);
formData.append(...);
fetch(url, { body: formData });
```

*shrug* It's not at all terrible, it's just more verbose than I thought we'd be able to get away with.

**Comment by annevk** [comment]
I would be happy for you to start and then we can work out a more ideal division once Credential Management has some cross-browser traction.

**Comment by mikewest** [comment]
Ok. Let me fire up the copy/paster then.

**Comment by annevk** [comment]
Note that one thing I suggested was that you make Credential a FormData subclass of sorts. That tackles extensibility by developers as well as discussed in #253. The only thing you'd need to allow for is to overwrite the names of username/password at a later stage if you want to cater to sites changing their `<form>` protocol.

**Comment by mikewest** [comment]
Hrm. Ok. I'd missed that subtlety. It seems like a complicated way of allowing developers to tack on extra data (and, also seems like something that I'd like to defer until after we've decided whether the entire concept makes sense).

Let me poke at this to see if there's a reasonably future-proof option, or if we'd really need to decide now whether to make `Credential` extensible in this kind of way.

**Comment by mikewest** [comment]
Hrm. I started spelling this out, and I'm not sure I like a few implications. `send()`, as currently defined:

1. Is locked to a PSL-matched origin with the `Credential`. That is, the username and password for `https://example.com/` can only be sent to `https://*.example.com/*`. (See step 4.1 of https://w3c.github.io/webappsec/specs/credentialmanagement/#send-passwordcredential).

2. Only sends cookies same-origin, skips redirects, and is POST-only (step 5 of https://w3c.github.io/webappsec/specs/credentialmanagement/#send-passwordcredential).

https://github.com/w3c/webappsec/issues/241#issuecomment-93454724 suggested "some restrictions on fetch() when used with opaque FormData", which I guess we could do. I suspect we'll continue to tweak these rules, though. To what extent can we really bake credential-type behavior into Fetch?

**Comment by annevk** [comment]
To whatever extent we deem necessary. The end game is either making `send()` look very similar to `fetch()` or just assimilating this thing into `fetch()` so we don't need the duplication. The latter seems somewhat nicer so any upgrades to `fetch()` automatically apply and we don't have to upgrade two methods all the time.

**Comment by mikewest** [comment]
38c55c8 take a first stab at this, moving the opaque `FormData` definition into CREDENTIAL, with all the attendant monkeypatching.

@annevk: What do you think about adding an `endpoint origin` slot (or something similar) to `FormData` which Fetch would examine before extracting a body (somewhere around step 32.1 of https://fetch.spec.whatwg.org/#dom-request)?

**Comment by annevk** [comment]
I guess that's reasonable. What do we do with service workers? (And don't forget about redirects.)

**Comment by mikewest** [comment]
1. I guess I'm not much worried by service workers, since they can already screw you over in a variety of ways. Allowing them to see the request body seems like the simplest solution. An alternative would be to bypass the service worker entirely for these kinds of requests, which I suppose might have some merit. *shrug* WDYT?

2. I plan to handle redirects by setting the `redirect` property to `error`. That, in combination with a "same-origin" flag of some sort would allow us to reject initial URLs that don't match the `FormData`'s origin, and then block redirects entirely. You either submit to the initial endpoint, or nowhere.

**Comment by annevk** [comment]
So if we already have a special `FormData` instance, why would we need this origin feature? As you say, if you supply this special instance we could just initialize `fetch()`'s request differently.

**Comment by mikewest** [comment]
Right now, I've simply defined an `opaque` flag on `FormData` (in https://w3c.github.io/webappsec/specs/credentialmanagement/#opaque-formdata). I guess it's not clear to me what "opaque to JavaScript" should also mean "can only submit to the same origin", and having a distinct flag for that behavior seemed reasonable. Would you prefer a single "do whatever the credentials spec needs" flag? Or a `CredentialFormData` object?

**Comment by annevk** [comment]
I think a distinct object might be better so we don't have to overload all the existing ways data gets exposed. But it's a bit unclear to me what the future of this object might be and what all the requirements are.

**Comment by mikewest** [comment]
Well, I think the changes to `FormData` are pretty small (one flag, which controls the behavior of `get()` and `getAll()`. The changes to `Request`/`Response` and `fetch()` are less clear to me, but I'm working through them. :)

How about I just do something, and then point you at it, and you can tell me I'm crazy.

**Comment by mikewest** [comment]
I've done something. Is it crazy, @annevk: https://w3c.github.io/webappsec/specs/credentialmanagement/#opaque-formdata

**Comment by annevk** [comment]
So you're not concerned with deletion or replacement? You haven't patched iteration. (Not sure how to patch that either, @bzbarsky might know or @heycam.)

**Comment by mikewest** [comment]
I guess I'm not concerned about deletion or replacement for the particular use case that's driving my interest in this feature. Worst case, the attacker doesn't log in, right?

For iteration, I meant to redefine the last sentence in the FormData definition to something like "The value pairs to iterate over is an empty list if the opaque flag is set, otherwise the entries with the key being the name and the value the value." Would that work?

**Comment by annevk** [comment]
Seems reasonable to me...

**Comment by mikewest** [comment]
Done in 580cb69.

**Comment by mikewest** [comment]
Ok, calling this done for the moment. Can open new bugs in the future if we need more changes.
