### ISSUE TITLE
CREDENTIAL: boolean acceptPasswords = true;

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#249]
Boolean arguments should not default to true.

**Comment by annevk** [comment]
Filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=28477 to track this at the IDL level.

**Comment by mikewest** [comment]
Why would `excludePasswords = false` be better? Double-negatives seem more difficult to understand than negated positives.

**Comment by annevk** [comment]
If some boolean arguments default to false and others to true, you have to study each method to know when you can omit the argument. I think the language quite consistently defaults to false. Also, the common case would be `excludePasswords = true` which does not seem hard to understand. 

However, you could also make it accept an enum. `passwords = "exclude"`.

**Comment by mikewest** [comment]
The underlying question is how to support extensibility. Right now we have `Local` and `Federated` credentials. Assume we have `MoonVector` credentials in the future that use your precise distance and direction from Earth's moon to determine who you are (did you know that each individual has a distinct vector from the moon? AMAZING.). Most websites won't accept this amazing new form of authentication at first, but someday they might _only_ accept this form.

Since we already have `federations` as a clear control on `FederatedCredential`, I wanted something similar for `LocalCredential`. Perhaps it would be siimpler to give a list of acceptable types, defaulting to everything the UA knows about?

**Comment by annevk** [comment]
Yeah that might be better since the whole setup assumes the user agent is going to be the middle man anyway.

**Comment by domenic** [comment]
+1 on boolean arguments defaulting to false.

List of acceptable types seems reasonable as well, although unsure whether it's better to create a string mapping (`accept: ["federated", "local"]`) or use the types directly (`accept: [FederatedCredential, LocalCredential]`).

LOL @ moon vectors ^_^

**Comment by mikewest** [comment]
I'm going to trivially resolve this by inverting the meaning of the boolean, and deal with the extensibility question as part of #256, which has substantial overlap with @domenic's `accept` proposal.
