### ISSUE TITLE
POWER: Privileged Contexts -> Secure Contexts

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#264]
Per @mikewest the rationale for the current name is OE. Given that OE is restricted to the `http` scheme it seems very clear that it is not HTTPS (Secure HTTP). Also, spelling privileged correctly is hard.

**Comment by mikewest** [comment]
@bcrypt: Any objections, illustrious co-editor?

**Comment by mikewest** [comment]
Er. @diracdeltas, apparently?

**Comment by torgo** [comment]
Is there still a chance to influence this? IMO “secure contexts” is a kind of circular name for this document. The original title “powerful features” makes more sense: these are powerful features that require a secure context – the emphasis being on the features and what constitutes a powerful feature. With “secure contexts” I'm not sure what we're talking about – lots of things might require a secure context (e.g. passing a credit card number), but what the document is about is the requirement of secure contexts for powerful web features. Focusing on the features is what makes sense to me. If you don't like “powerful” how about “privacy-sensitive”? “Need for Secure Context for Privacy-Sensitive Features” maybe?

**Comment by annevk** [comment]
Secure Context as in Secure HTTP but then for browsing contexts et al. Not sure how that does not make sense.

Powerful features does not work since we want to use this for non-powerful features too. And nobody can agree on what powerful features means anyway. So better to focus on the context and not the features.

**Comment by torgo** [comment]
Sorry but I still don't get how it *does* make sense. When I try to describe it to developers, the "aha moment" is when I talk about features that are in some way more – won't use the p-word – dangerous / potential privacy infringing / intrusive / fraught. If we just say “secure contexts” then we could be talking about anything. The whole point here is that more of these kinds of features are making their way into the web and they should be limited to a TLS context. 

Sorry to be adding bike-shedding energy here but I do actually think this smatters because it frames the document and makes it clear why we're doing this. It also makes it more explainable.

**Comment by diracdeltas** [comment]
I am okay with either name.

**Comment by annevk** [comment]
What bit doesn't make use? There's browsing contexts, some are secure, some are not.

Given that Mozilla is considering restricting all new features to secure contexts, I don't think we can reasonably make a feature-based classification, and we need a context-based classification either way.

**Comment by mikewest** [comment]
We went with "Secure Contexts".
