### ISSUE TITLE
CREDENTIAL: document the reducing the carousel use case

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#272]
Currently sites that offer federated login have a large amount of options for the user to choose from. And next time you visit you might forget which one you picked.

The functionality in this draft solves both problems. It allows a site to ask the user to pick a federated login through user agent mediation so that the user is only confronted with those sites they actually use. And it allows a site to store the result of the mediation.

**Comment by adrianhopebailie** [comment]
>It allows a site to ask the user to pick a federated login through user agent mediation so that the user is only confronted with those sites they actually use. 

Does it solve this? It seems to me that origin-based restrictions mean that the site is only presented with `FederatedCredential` instances that same site has stored previously. The limited set of federated identity providers the user actually uses (on other sites) is unknown to the site initially. i.e. The user must still select from the large set of options when they first register for the site. 

This API does at least help the user remember which one they picked  when they return (the second problem).

**Comment by annevk** [comment]
Yes it does. It's just that those would require permission from the user before being shared.

**Comment by adrianhopebailie** [comment]
I mis-understood the algorithm. [This](https://w3c.github.io/webappsec/specs/credentialmanagement/#user-mediated-selection) part of the spec makes it much clearer.

I would agree with the issue then that it's not obvious that this API assists sites offering federated login from avoiding the "nascar"/"carousel" problem. An example of this would be helpful, showing the full flow of visiting a federated IdP site that stores the credential and then registration on a site that uses that federated login. Will try to put something together.

This raises the following questions:

1. How should the browser behave if a site attempts to store a FederatedCredential with a `federation` that is different from it's own origin?
1. Does the `id` property of the `FederatedCredential` represent the user's id at the IdP or on the RP site that stored the `FederatedCredential` (assuming these are different and the IdP never stored the credential but the RP did).
1. If a RP site stores a `FederatedCredential` does that mean it can be shared with other sites (assuming the user gives permission) when they request a `FederatedCredential` with the same `federation` property? i.e. A site defines a credential that they claim is from a 3rd party IdP and then other sites consume it not knowing who issued it.

**Comment by mikewest** [comment]
1. Aren't all federations distinct from the site's origin? That is, I'm using `facebook.com` on `example.com`? Otherwise it's not a `FederatedCredential`.

2. ID at the IdP, as a hint for the sign-in process if you happen to be signed in with multiple accounts.

3. I didn't plan to support that use case, but you could certainly imagine that user agents could come up with interesting heuristics to determine whether or not a `FederatedCredential` could be synthesized. Logging into various websites with Facebook, even if I haven't stored a Facebook password, might be a good signal. Likewise, user agents could dig through the locally-stored browsing history for hints.

On the one hand, I don't want to overspecify how things work (as most of it will be vendor-specific), but I completely agree with both of you that it's currently underspecified. :)

**Comment by adrianhopebailie** [comment]
> Aren't all federations distinct from the site's origin? That is, I'm using facebook.com on example.com? Otherwise it's not a FederatedCredential.

I'm confused. Who would normally store the `FederatedCredential` the IdP site or the RP site? I.e. Can `example.com` store a credential which states `facebook.com` is the federation?

It would make sense for it to be the IdP that does the storing, but nothing (as far as I can tell) is currently stopping the RP from also doing so. i.e. There is no rule that says you can only store a `FederatedCredential` if the `federation` property matches your origin.

Somewhat linked to #266 because in that instance the IdP origin may be `openidconnectcompliantidp.com` but that's not really useful to a RP site that is happy to get any `FederatedCredential` as long as it's from an IdP that supports the Open ID Connect protocol.

**Comment by mikewest** [comment]
In this model, the `FederatedCredential` is stored by the relying party. That is, `example.com` is asserting that the user just used `federation.com` to sign in by doing something like:

```
navigator.credentials.store(new FederatedCredential("mike@mikewest.org", "https://federation.com/"));
```

The IdP should not be responsible for storing credential on other origins. That seems like a model rife for abuse (e.g. Facebook says "Hey, you should log in with me!" and attempts to set credentials for every site you're likely to go to.)

**Comment by mikewest** [comment]
(I'd missed #266, sorry. I'll skim it later this afternoon.)

**Comment by adrianhopebailie** [comment]
>The IdP should not be responsible for storing credential on other origins. That seems like a model rife for abuse (e.g. Facebook says "Hey, you should log in with me!" and attempts to set credentials for every site you're likely to go to.)

You and @annevk seem to be saying different things. He is asserting that this API solves the "nascar" problem but it can't if the RP has to offer the user all IdP options first and only after they have logged in store the `Credential` for the next time.

If, on the other hand, the IdP can store the fact that the user has a `FederatedCredential` for their site and the `get()` method returns these credentials to RP sites following user mediation there is an opportunity to present the user with only the federated identity providers they actually use.

**Comment by mikewest** [comment]
I've tried to clarify this in w3c/webappsec@8fafb06 (the heart of which is more easily viewed at file:///usr/local/google/home/mkwst/Repositories/webappsec/specs/credentialmanagement/index.html#synthesis).

**Comment by jmajnert** [comment]
You probably meant https://w3c.github.io/webappsec/specs/credentialmanagement/#synthesis
:-)

**Comment by mikewest** [comment]
Hrm. I might have meant that, yes. :/
