### ISSUE TITLE
REFERRER: `origin` shouldn't send a trailing `/`.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#382]
We don't send a trailing `/` for the `Origin` header, so I think we should change our minds about the behavior here. We should strip the trailing `/` character as part of step 6 of https://w3c.github.io/webappsec/specs/referrer-policy/#strip-url.

**Comment by kristijanburnik** [comment]
It has to do with the question if the URL is valid without the slash for the path.

```
Note: The serialization of an origin looks like https://example.com. 
To ensure that a valid URL is sent in the `Referer` header, 
user agents will append a U+002F SOLIDUS ("/") character to the origin 
(e.g. https://example.com/).
```

According to [RFC 3986 section-3.3](https://tools.ietf.org/html/rfc3986#section-3.3), the path can be empty and it should still form a valid URL.

The [RFC 7231 section-5.5.2](http://tools.ietf.org/html/rfc7231#section-5.5.2) touches on the topic but I couldn't find a spec saying that the slash is mandatory. 

**Is this a chrome artifact?**

I did some more research and according to PHP:

```php
<?php

$urls = array("http://example.com", "http://example.com/");

foreach ($urls as $url) {
  if (filter_var($url, FILTER_VALIDATE_URL) !== FALSE) {
    echo "VALID: $url\n";
  } else {
    echo "INVALID: $url\n";
  }
  print_r(parse_url($url));
  echo "\n";
}
```
This script outputs:

```
VALID: http://example.com
Array
(
    [scheme] => http
    [host] => example.com
)

VALID: http://example.com/
Array
(
    [scheme] => http
    [host] => example.com
    [path] => /
)
```

Since both HTTP Origin and document.origin omit the slash, I agree that a consistent form should be used. :-)

**Comment by mikewest** [comment]
Looking at this again, I now agree with myself from the past.

The `origin` header is a serialized origin. The `referer` header is not an origin; it's a URL that we happen to be stripping down to an origin. https://tools.ietf.org/html/rfc7231#section-5.5.2 defines the ABNF as an `absolute-URI` or `partial-URI`. I don't think there's a need to strip the `/` at the end, given that we're representing an URI, and given that both Chrome and Firefox already implemented things with the `/`.

**Comment by kristijanburnik** [comment]
Ok, since both implement the trailing "/", I guess we should stick to it
for the sake of BC.

I will remove the related comment in the JS test wrapper at the earliest
convenience:
https://github.com/kristijanburnik/web-platform-tests/blob/referrer-policy-test-case/referrer-policy/generic/referrer-policy-test-case.js#L54




On Thu, May 21, 2015 at 4:45 PM, Mike West <notifications@github.com> wrote:

> Looking at this again, I now agree with myself from the past.
>
> The origin header is a serialized origin. The referer header is not an
> origin; it's a URL that we happen to be stripping down to an origin.
> https://tools.ietf.org/html/rfc7231#section-5.5.2 defines the ABNF as an
> absolute-URI or partial-URI. I don't think there's a need to strip the /
> at the end, given that we're representing an URI, and given that both
> Chrome and Firefox already implemented things with the /.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/webappsec/issues/382#issuecomment-104304539>.
>



-- 

*Kristijan Burnik*

Software Engineer Intern

burnik@google.com
+385 91 4846 379

Google Germany GmbH

Dienerstraße 12

80331 München

Geschäftsführer: Graham Law, Christine Elizabeth Flores

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

Diese E-Mail ist vertraulich. Wenn Sie nicht der richtige Adressat sind,
leiten Sie diese bitte nicht weiter, informieren Sie den Absender und
löschen Sie die E-Mail und alle Anhänge. Vielen Dank.



This e-mail is confidential. If you are not the right addressee please do
not forward it, please inform the sender, and please erase this e-mail
including any attachments. Thanks.

**Comment by franziskuskiefer** [comment]
> I don't think there's a need to strip the / at the end, given that we're representing an URI, and given that both Chrome and Firefox already implemented things with the /.

that's actually not true, Firefox does not send the trailing slash for the origin referer header or the origin header

**Comment by kristijanburnik** [comment]
Ok, As I recall, my claim did hold a few weeks ago...
Not sure if I've poorly manually tested the thing or FF had it changed in
the mean time...

@Mike:
Also, I'm not sure if I should be updating the Referrer Policy tests in
WPT,
I guess we should wait for the spec to decide?





On Tue, Jul 21, 2015 at 6:59 PM, Franziskus Kiefer <notifications@github.com
> wrote:

> I don't think there's a need to strip the / at the end, given that we're
> representing an URI, and given that both Chrome and Firefox already
> implemented things with the /.
>
> that's actually not true, Firefox does not send the trailing slash for the
> origin referer header or the origin header
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/webappsec/issues/382#issuecomment-123402395>.
>



-- 

*Kristijan Burnik*

Software Engineering Intern

burnik@google.com

Google Germany GmbH

Dienerstraße 12

80331 München

Geschäftsführer: Graham Law, Christine Elizabeth Flores

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

**Comment by annevk** [comment]
I think for Referrer we should always send a serialized URL, which will always include a trailing slash for HTTP URLs.

**Comment by franziskuskiefer** [comment]
If `Referer` is an origin, then origin serialisation [1] would not add a trailing `/` (that's what the `Origin` header is doing)

[1] https://html.spec.whatwg.org/multipage/browsers.html#ascii-serialisation-of-an-origin

**Comment by annevk** [comment]
Oh, we use origin serialization? I figured we'd just null the path, query, and fragment components and then serialize. I guess can go either way I guess. Always serializing `Referer` as a URL made sense to me, but it doesn't matter much.

**Comment by briansmith** [comment]
I think it probably will matter as far as compatibility is concerned. Referer has always had the trailing slash when the referrer is the home page of a site, so every non-empty Referer (I think) has at least one slash, and I'm sure people have written regexes and whatnot that expect that.

The origin header is a different matter. It shouldn't have a slash because the syntax for an origin isn't a URL.

**Comment by franziskuskiefer** [comment]
I agree, this is only a compatibility issue regarding the `Referer` header. Since the `Referer` usually seem to contain the trailing `/` (checked Firefox and Chrome), we should do this in case a referrer policy is set as well, i.e. Firefox should get fixed (filed a bug).
