### ISSUE TITLE
SECURE: Consider expanding definition of "potentially trustworthy".

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#478]
Perhaps we could include special-use domains like `*.localhost` and `*.test` alongside `localhost` and `127.0.0.1` as carve-outs for developers?

WDYT: @noncombatant, @sleevi?

**Comment by sleevi** [comment]
There is no requirement for a DNS resolver to not transmit resolution requests for these names to the network.

If a DNS resolver does, then it is not secure.

There are several major operating systems that will transmit resolution requests for such names to the network.

As such, they are only secure if a user agent substitutes its own resolver.

Chromium has not had a great experience - nor have users - in our attempts to. We do substitute our own room solver, except it is difficult to impossible to 1:1 match the OS resolver and what users expect, but without causing the security issues.

Simply filtering such requests also doesn't work as users expect (e.g. doesn't respect /etc/hosts or nsswitch).

I think it would be a very bad idea to allow those domains, for security reasons, because of this.

**Comment by mikewest** [comment]
`.localhost` requests hit the internet? Really? *sigh*
