### ISSUE TITLE
CSP: Specification of report-uri misleading

### ISSUE THREAD

**Issue by sbrewell** [w3c/webappsec#521]
The CSP specification section 7.13 states:

"The set of report URLs is the value of the report-uri directive, each resolved relative to the protected resource’s URL."

This is misleading as a) the RFC 3986 states that a URI reference can be an absolute URI or relative path, and b) sites like report-uri.io wouldn't be able to function - and they do.

**Comment by ScottHelme** [comment]
Is this just a typo in the spec @mikewest?

**Comment by mikewest** [comment]
It looks like you're looking at CSP2. It's probably a better idea to look at https://w3c.github.io/webappsec-csp/#directive-report-uri and https://w3c.github.io/webappsec-csp/#report-violation. The latter parses the URL in step 3.4.2. As it turns out, that has the opposite bug: we ought to be passing the page's URL into the parser there. I'll take care of that shortly.

In short: parsing a relative URL uses the page's URL to resolve the origin and path. Parsing an absolute URL (`https://example.com/whatever`) does not use the base URL at all. https://url.spec.whatwg.org/#url-parsing spells it out, but it's a little complicated to parse. Trust me. ;)

**Comment by sbrewell** [comment]
CSP3 is in draft though, CSP2 is still current and should be correct should't it?

**Comment by mikewest** [comment]
CSP2 hasn't been substantially updated in ~3 years. The last paragraph of https://www.w3.org/TR/CSP2/#status explains things. Not as clearly as I'd like, but as clearly as I could get W3C folks to agree to.

I've updated CSP3 to pass in the base URL. I'm pretty sure that the text in CSP2 is correct. It could certainly be clearer, but I don't think it's worth going back and making changes to that old snapshot. CSP3 is where it's at these days. :)

**Comment by mikewest** [comment]
Ok? I'm not sure I understand why, but I look forward to seeing your issue!

https://github.com/w3c/webappsec-csp/ is a better repo to file bugs on than this one, by the way.
