### ISSUE TITLE
Planning 2024-06-19

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec#652]
Agenda wrangling for the June 19 WebAppSec meeting

**Comment by marcoscaceres** [comment]
Could we add small item to the agenda about dropping "webappsec-*" from the from the repo names? "webappsec-" makes the repos difficult to find and somewhat annoying to type with already long repo names (e.g., "webappsec-credential-management"). Ideally, the name of the repository should match the "short name" of the spec. 

No other group does this and specs often get moved from one working group to another. 

In order to make the transition go smoothly, we just need to add redirects as needed to:
https://github.com/w3c/w3c.github.io

I know this seems like busy work, but it makes a big difference to folks who need to be interacting with these repos on a daily basis. 🙏 

(I'll even volunteer to handle any redirects for specs that affect me, like Cred Man, and Permissions Policy, etc.)

**Comment by jonathanKingston** [comment]
With two shipping implementations of upgrading, what else is needed to move mixed-content to CR?

**Comment by dveditz** [comment]
We dropped this meeting in favor of July.
